package com.github.finley243.adventureengine.script;

public enum HighlightType {
    KEYWORD, OPERATOR, COMMENT,
    STRING, NUMBER, BOOLEAN, NULL,
    VARIABLE, FUNCTION_CALL, FUNCTION_DEFINITION_NAME,
    PARAMETER_DEFINITION, NAMED_PARAMETER_REFERENCE,
    MEMBER_NAME, PARAMETER_ASSIGNMENT
}
